# Write your MySQL query statement below
SELECT P.PRODUCT_ID,PRODUCT_NAME FROM PRODUCT P JOIN SALES S ON P.PRODUCT_ID = S.PRODUCT_ID WHERE (SALE_DATE BETWEEN '2019-01-01' AND '2019-03-31') 
EXCEPT
SELECT P.PRODUCT_ID,PRODUCT_NAME FROM PRODUCT P JOIN SALES S ON P.PRODUCT_ID = S.PRODUCT_ID WHERE NOT (SALE_DATE BETWEEN '2019-01-01' AND '2019-03-31')